### ISSUE TITLE
Create an account with a nickname

### ISSUE THREAD

**Issue by davidbgk** [etalab/id.data.gouv.fr#1]
As a user, when I'm redirected to ID I should be able to create an account with nickname, email and password.

TODO: add the ability to specify a nickname.

**Comment by davidbgk** [comment]
After discussing with @vinyll we wonder if we actually need a nickname. The main reason we wanted a nickname was to ensure anonymous user from the SSO to the client regarding the CNIL.

We propose to put the `email` into a scope as previously discussed and to only return an ID if the email is not asked by the client service. This way the user is informed that his email will be passed to the client service and can refuse the identification in that case.

Anyway, we should always return the unique ID of the user to the client service in case the email changes over time. So the client service should only rely on that ID.

If a client service needs a nickname, it should be asked during the second part of the registration directly on the client service side (maybe with more pertinent information specific to that given service).

**Comment by jdesboeufs** [comment]
I totally agree with you 👍

**Comment by romtal** [comment]
Good suggestion ;) i also agree with u guys 👌

**Comment by vinyll** [comment]
Seems like a unique ID and an email are enough for 3rd party apps for now.
